[
  {
    "package": {
      "name": "pygments",
      "version": "2.11.1",
      "ecosystem": "PyPI"
    },
    "vulnerabilities": [
      {
        "modified": "2024-10-24T22:27:47Z",
        "published": "2023-07-19T15:30:26Z",
        "schema_version": "1.6.0",
        "id": "GHSA-mrwq-x4v8-fh7p",
        "aliases": [
          "CVE-2022-40896",
          "PYSEC-2023-117"
        ],
        "summary": "Pygments vulnerable to ReDoS",
        "details": "A ReDoS issue was discovered in `pygments/lexers/smithy.py` in Pygments until 2.15.0 via SmithyLexer.",
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
          },
          {
            "type": "CVSS_V4",
            "score": "CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:P/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N"
          }
        ],
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pygments",
              "purl": "pkg:pypi/pygments"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "2.15.0"
                  }
                ]
              }
            ],
            "versions": [
              "0.10",
              "0.11",
              "0.11.1",
              "0.5",
              "0.5.1",
              "0.6",
              "0.7",
              "0.7.1",
              "0.8",
              "0.8.1",
              "0.9",
              "1.0",
              "1.1",
              "1.1.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.3",
              "1.3.1",
              "1.4",
              "1.5",
              "1.6",
              "1.6rc1",
              "2.0",
              "2.0.1",
              "2.0.2",
              "2.0rc1",
              "2.1",
              "2.1.1",
              "2.1.2",
              "2.1.3",
              "2.10.0",
              "2.11.0",
              "2.11.1",
              "2.11.2",
              "2.12.0",
              "2.13.0",
              "2.14.0",
              "2.2.0",
              "2.3.0",
              "2.3.1",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.5.1",
              "2.5.2",
              "2.6.0",
              "2.6.1",
              "2.7.0",
              "2.7.1",
              "2.7.2",
              "2.7.3",
              "2.7.4",
              "2.8.0",
              "2.8.1",
              "2.9.0"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/07/GHSA-mrwq-x4v8-fh7p/GHSA-mrwq-x4v8-fh7p.json"
            }
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40896"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pygments/pygments/commit/97eb3d5ec7c1b3ea4fcf9dee30a2309cf92bd194"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pygments/pygments/commit/dd52102c38ebe78cd57748e09f38929fd283ad04"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pygments/pygments/commit/fdf182a7af85b1deeeb637ca970d31935e7c9d52"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/pygments/pygments"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pygments/PYSEC-2023-117.yaml"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EZGMXALE3HSP4OXC7UUWIKX3OXKZDTY3"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VUZO4BQCIY2S2KZYHERQMKURB7AHXDBO"
          },
          {
            "type": "WEB",
            "url": "https://pypi.org/project/Pygments"
          },
          {
            "type": "WEB",
            "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-434"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-07-20T11:00:04Z",
          "nvd_published_at": "2023-07-19T15:15:10Z",
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2023-11-08T04:10:25Z",
        "published": "2023-07-19T15:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-117",
        "aliases": [
          "CVE-2022-40896",
          "GHSA-mrwq-x4v8-fh7p"
        ],
        "details": "A ReDoS issue was discovered in pygments/lexers/smithy.py in pygments through 2.15.0 via SmithyLexer.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pygments",
              "purl": "pkg:pypi/pygments"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "2.15.1"
                  }
                ]
              }
            ],
            "versions": [
              "0.10",
              "0.11",
              "0.11.1",
              "0.5",
              "0.5.1",
              "0.6",
              "0.7",
              "0.7.1",
              "0.8",
              "0.8.1",
              "0.9",
              "1.0",
              "1.1",
              "1.1.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.3",
              "1.3.1",
              "1.4",
              "1.5",
              "1.6",
              "1.6rc1",
              "2.0",
              "2.0.1",
              "2.0.2",
              "2.0rc1",
              "2.1",
              "2.1.1",
              "2.1.2",
              "2.1.3",
              "2.10.0",
              "2.11.0",
              "2.11.1",
              "2.11.2",
              "2.12.0",
              "2.13.0",
              "2.14.0",
              "2.15.0",
              "2.2.0",
              "2.3.0",
              "2.3.1",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.5.1",
              "2.5.2",
              "2.6.0",
              "2.6.1",
              "2.7.0",
              "2.7.1",
              "2.7.2",
              "2.7.3",
              "2.7.4",
              "2.8.0",
              "2.8.1",
              "2.9.0"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pygments/PYSEC-2023-117.yaml"
            }
          }
        ],
        "references": [
          {
            "type": "PACKAGE",
            "url": "https://pypi.org/project/Pygments/"
          },
          {
            "type": "WEB",
            "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2/"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "PYSEC-2023-117",
          "GHSA-mrwq-x4v8-fh7p"
        ],
        "aliases": [
          "CVE-2022-40896",
          "GHSA-mrwq-x4v8-fh7p",
          "PYSEC-2023-117"
        ],
        "max_severity": "6.8"
      }
    ]
  },
  {
    "package": {
      "name": "sqlparse",
      "version": "0.4.4",
      "ecosystem": "PyPI"
    },
    "vulnerabilities": [
      {
        "modified": "2025-02-16T05:57:35Z",
        "published": "2024-04-15T20:21:25Z",
        "schema_version": "1.6.0",
        "id": "GHSA-2m57-hf25-phgg",
        "aliases": [
          "CVE-2024-4340"
        ],
        "related": [
          "CGA-p7rq-qffc-ch9v",
          "CGA-v3hx-x533-rpgf",
          "CVE-2024-4340"
        ],
        "summary": "sqlparse parsing heavily nested list leads to Denial of Service",
        "details": "### Summary\nPassing a heavily nested list to sqlparse.parse() leads to a Denial of Service due to RecursionError.\n\n### Details + PoC\nRunning the following code will raise Maximum recursion limit exceeded exception:\n```py\nimport sqlparse\nsqlparse.parse('[' * 10000 + ']' * 10000)\n```\nWe expect a traceback of RecursionError:\n```py\nTraceback (most recent call last):\n  File \"trigger_sqlparse_nested_list.py\", line 3, in <module>\n    sqlparse.parse('[' * 10000 + ']' * 10000)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/__init__.py\", line 30, in parse\n    return tuple(parsestream(sql, encoding))\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/filter_stack.py\", line 36, in run\n    stmt = grouping.group(stmt)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 428, in group\n    func(stmt)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 53, in group_brackets\n    _group_matching(tlist, sql.SquareBrackets)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 48, in _group_matching\n    tlist.group_tokens(cls, open_idx, close_idx)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 328, in group_tokens\n    grp = grp_cls(subtokens)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 161, in __init__\n    super().__init__(None, str(self))\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 165, in __str__\n    return ''.join(token.value for token in self.flatten())\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 165, in <genexpr>\n    return ''.join(token.value for token in self.flatten())\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  [Previous line repeated 983 more times]\nRecursionError: maximum recursion depth exceeded\n```\n\n### Fix suggestion\nThe [flatten()](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/sql.py#L207) function of TokenList class should limit the recursion to a maximal depth:\n```py\nfrom sqlparse.exceptions import SQLParseError\n\nMAX_DEPTH = 100\n\n    def flatten(self, depth=1):\n        \"\"\"Generator yielding ungrouped tokens.\n\n        This method is recursively called for all child tokens.\n        \"\"\"\n    if depth >= MAX_DEPTH:\n        raise SQLParseError('Maximal depth reached')\n        for token in self.tokens:\n            if token.is_group:\n                yield from token.flatten(depth + 1)\n            else:\n                yield token\n```\n\n### Impact\nDenial of Service (the impact depends on the use).\nAnyone parsing a user input with sqlparse.parse() is affected.\n",
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "sqlparse",
              "purl": "pkg:pypi/sqlparse"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "0.5.0"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.0",
              "0.1.1",
              "0.1.10",
              "0.1.11",
              "0.1.12",
              "0.1.13",
              "0.1.14",
              "0.1.15",
              "0.1.16",
              "0.1.17",
              "0.1.18",
              "0.1.19",
              "0.1.2",
              "0.1.3",
              "0.1.4",
              "0.1.5",
              "0.1.6",
              "0.1.7",
              "0.1.8",
              "0.1.9",
              "0.2.0",
              "0.2.1",
              "0.2.2",
              "0.2.3",
              "0.2.4",
              "0.3.0",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "0.4.2",
              "0.4.3",
              "0.4.4"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/04/GHSA-2m57-hf25-phgg/GHSA-2m57-hf25-phgg.json"
            }
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-2m57-hf25-phgg"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-4340"
          },
          {
            "type": "WEB",
            "url": "https://github.com/andialbrecht/sqlparse/commit/b4a39d9850969b4e1d6940d32094ee0b42a2cf03"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/andialbrecht/sqlparse"
          },
          {
            "type": "WEB",
            "url": "https://research.jfrog.com/vulnerabilities/sqlparse-stack-exhaustion-dos-jfsa-2024-001031292"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-674"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-04-15T20:21:25Z",
          "nvd_published_at": null,
          "severity": "HIGH"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-2m57-hf25-phgg"
        ],
        "aliases": [
          "CVE-2024-4340",
          "GHSA-2m57-hf25-phgg"
        ],
        "max_severity": "7.5"
      }
    ]
  }
]