[
  {
    "package": {
      "name": "gitpython",
      "version": "3.1.34",
      "ecosystem": "PyPI",
      "commit": ""
    },
    "vulnerabilities": [
      {
        "modified": "2023-10-10T19:55:09Z",
        "published": "2023-08-30T20:09:36Z",
        "schema_version": "1.6.0",
        "id": "GHSA-cwvm-v4w8-q58c",
        "aliases": [
          "CVE-2023-41040"
        ],
        "summary": "Blind local file inclusion",
        "details": "### Summary\n\nIn order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system.\n\n### Details\n\nThis vulnerability is present in\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175\n\nThat code joins the base directory with a user given string without checking if the final path is located outside the base directory.\n\nI was able to exploit it from three places, but there may be more code paths that lead to it:\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/repo/base.py#L605\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/repo/base.py#L620\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/index/base.py#L1353\n\n### PoC\n\nRunning GitPython within any repo should work, here is an example with the GitPython repo.\n\n```python\nimport git\n\nr = git.Repo(\".\")\n\n# This will make GitPython read the README.md file from the root of the repo\nr.commit(\"../README.md\")\nr.tree(\"../README.md\")\nr.index.diff(\"../README.md\")\n\n# Reading /etc/random\n# WARNING: this will probably halt your system, run with caution\n# r.commit(\"../../../../../../../../../dev/random\")\n```\n\n### Impact\n\nI wasn't able to show the contents of the files (that's why \"blind\" local file inclusion), depending on how GitPython is being used, this can be used by an attacker for something _inoffensive_ as checking if a file exits, or cause a DoS by making GitPython read a big/infinite file (like `/dev/random` on Linux systems).\n\n### Possible solutions\n\nA solution would be to check that the final path isn't located outside the `repodir` path (maybe even after resolving symlinks). Maybe there could be other checks in place to make sure that the reference names are valid.\n\n---\n\n> [!NOTE]\n> This vulnerability was reported via email, and it was decided to publish it here and make it public, so the community is aware of it, and a fix can be provided.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.37"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.33",
              "3.1.34",
              "3.1.35",
              "3.1.36",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "last_known_affected_version_range": "<= 3.1.36",
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-cwvm-v4w8-q58c/GHSA-cwvm-v4w8-q58c.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-41040"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1672"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/commit/74e55ee4544867e1bd976b7df5a45869ee397b0b"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/gitpython-developers/GitPython"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-165.yaml"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-22"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-08-30T20:09:36Z",
          "nvd_published_at": null,
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2023-09-07T14:33:25Z",
        "published": "2023-08-30T22:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-165",
        "aliases": [
          "CVE-2023-41040",
          "GHSA-cwvm-v4w8-q58c"
        ],
        "details": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.35"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.33",
              "3.1.34",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/gitpython/PYSEC-2023-165.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-cwvm-v4w8-q58c",
          "PYSEC-2023-165"
        ]
      }
    ]
  },
  {
    "package": {
      "name": "urllib3",
      "version": "2.0.4",
      "ecosystem": "PyPI",
      "commit": ""
    },
    "vulnerabilities": [
      {
        "modified": "2023-10-17T20:34:07Z",
        "published": "2023-10-17T20:15:25Z",
        "schema_version": "1.6.0",
        "id": "GHSA-g4mx-q9vg-27p4",
        "aliases": [
          "CVE-2023-45803"
        ],
        "summary": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
        "details": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.\n",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.7"
                  }
                ]
              }
            ],
            "versions": [
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6"
            ],
            "database_specific": {
              "last_known_affected_version_range": "<= 2.0.6",
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-g4mx-q9vg-27p4/GHSA-g4mx-q9vg-27p4.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                ""
              ]
            }
          },
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.18"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.17",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1"
            ],
            "database_specific": {
              "last_known_affected_version_range": "<= 1.26.17",
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-g4mx-q9vg-27p4/GHSA-g4mx-q9vg-27p4.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                ""
              ]
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/urllib3/urllib3"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/releases/tag/1.26.18"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/releases/tag/2.0.7"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-200"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-10-17T20:15:25Z",
          "nvd_published_at": null,
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2023-10-13T22:03:00Z",
        "published": "2023-10-02T23:27:05Z",
        "schema_version": "1.6.0",
        "id": "GHSA-v845-jxx5-vc9f",
        "aliases": [
          "CVE-2023-43804"
        ],
        "summary": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
        "details": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.6"
                  }
                ]
              }
            ],
            "versions": [
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-v845-jxx5-vc9f/GHSA-v845-jxx5-vc9f.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                ""
              ]
            }
          },
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.17"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-v845-jxx5-vc9f/GHSA-v845-jxx5-vc9f.json"
            },
            "ecosystem_specific": {
              "affected_functions": [
                ""
              ]
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/urllib3/urllib3"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-200"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-10-02T23:27:05Z",
          "nvd_published_at": null,
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2023-10-10T14:28:19Z",
        "published": "2023-10-04T17:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-192",
        "aliases": [
          "CVE-2023-43804",
          "GHSA-v845-jxx5-vc9f"
        ],
        "details": "urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "644124ecd0b6e417c527191f866daa05a5a2056d"
                  },
                  {
                    "fixed": "01220354d389cd05474713f8c982d05c9b17aafb"
                  }
                ],
                "repo": "https://github.com/urllib3/urllib3"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.6"
                  },
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.17"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/urllib3/PYSEC-2023-192.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N"
          }
        ],
        "references": [
          {
            "type": "FIX",
            "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
          },
          {
            "type": "ADVISORY",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
          },
          {
            "type": "FIX",
            "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-g4mx-q9vg-27p4"
        ]
      },
      {
        "ids": [
          "GHSA-v845-jxx5-vc9f",
          "PYSEC-2023-192"
        ]
      }
    ]
  }
]