[
  {
    "package": {
      "name": "pygments",
      "version": "2.5.2",
      "ecosystem": "PyPI"
    },
    "vulnerabilities": [
      {
        "modified": "2023-04-11T01:49:22Z",
        "published": "2021-04-20T16:35:47Z",
        "schema_version": "1.4.0",
        "id": "GHSA-9w8r-397f-prfh",
        "aliases": [
          "CVE-2021-20270"
        ],
        "summary": "Infinite Loop in Pygments",
        "details": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pygments",
              "purl": "pkg:pypi/pygments"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "1.5"
                  },
                  {
                    "fixed": "2.7.4"
                  }
                ]
              }
            ],
            "versions": [
              "1.5",
              "1.6",
              "1.6rc1",
              "2.0",
              "2.0.1",
              "2.0.2",
              "2.0rc1",
              "2.1",
              "2.1.1",
              "2.1.2",
              "2.1.3",
              "2.2.0",
              "2.3.0",
              "2.3.1",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.5.1",
              "2.5.2",
              "2.6.0",
              "2.6.1",
              "2.7.0",
              "2.7.1",
              "2.7.2",
              "2.7.3"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/04/GHSA-9w8r-397f-prfh/GHSA-9w8r-397f-prfh.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-20270"
          },
          {
            "type": "WEB",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1922136"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
          },
          {
            "type": "WEB",
            "url": "https://www.debian.org/security/2021/dsa-4889"
          },
          {
            "type": "WEB",
            "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-835"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2021-04-12T20:58:03Z",
          "nvd_published_at": "2021-03-23T17:15:00Z",
          "severity": "HIGH"
        }
      },
      {
        "modified": "2023-04-11T01:33:30Z",
        "published": "2021-03-29T16:33:03Z",
        "schema_version": "1.4.0",
        "id": "GHSA-pq64-v7f5-gqh8",
        "aliases": [
          "CVE-2021-27291"
        ],
        "summary": "Regular Expression Denial of Service (ReDoS) in Pygments",
        "details": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pygments",
              "purl": "pkg:pypi/pygments"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "1.1"
                  },
                  {
                    "fixed": "2.7.4"
                  }
                ]
              }
            ],
            "versions": [
              "1.1",
              "1.1.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.3",
              "1.3.1",
              "1.4",
              "1.5",
              "1.6",
              "1.6rc1",
              "2.0",
              "2.0.1",
              "2.0.2",
              "2.0rc1",
              "2.1",
              "2.1.1",
              "2.1.2",
              "2.1.3",
              "2.2.0",
              "2.3.0",
              "2.3.1",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.5.1",
              "2.5.2",
              "2.6.0",
              "2.6.1",
              "2.7.0",
              "2.7.1",
              "2.7.2",
              "2.7.3"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/03/GHSA-pq64-v7f5-gqh8/GHSA-pq64-v7f5-gqh8.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-27291"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14"
          },
          {
            "type": "WEB",
            "url": "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/pygments/pygments"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/"
          },
          {
            "type": "WEB",
            "url": "https://www.debian.org/security/2021/dsa-4878"
          },
          {
            "type": "WEB",
            "url": "https://www.debian.org/security/2021/dsa-4889"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-400"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2021-03-22T20:28:40Z",
          "nvd_published_at": "2021-03-17T13:15:00Z",
          "severity": "HIGH"
        }
      },
      {
        "modified": "2021-08-27T03:22:17Z",
        "published": "2021-03-23T17:15:00Z",
        "schema_version": "1.4.0",
        "id": "PYSEC-2021-140",
        "aliases": [
          "CVE-2021-20270",
          "GHSA-9w8r-397f-prfh"
        ],
        "details": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pygments",
              "purl": "pkg:pypi/pygments"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "1.5"
                  },
                  {
                    "fixed": "2.7.4"
                  }
                ]
              }
            ],
            "versions": [
              "1.5",
              "1.6",
              "1.6rc1",
              "2.0",
              "2.0.1",
              "2.0.2",
              "2.0rc1",
              "2.1",
              "2.1.1",
              "2.1.2",
              "2.1.3",
              "2.2.0",
              "2.3.0",
              "2.3.1",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.5.1",
              "2.5.2",
              "2.6.0",
              "2.6.1",
              "2.7.0",
              "2.7.1",
              "2.7.2",
              "2.7.3"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pygments/PYSEC-2021-140.yaml"
            }
          }
        ],
        "references": [
          {
            "type": "REPORT",
            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1922136"
          },
          {
            "type": "ADVISORY",
            "url": "https://www.debian.org/security/2021/dsa-4889"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
          },
          {
            "type": "ADVISORY",
            "url": "https://github.com/advisories/GHSA-9w8r-397f-prfh"
          }
        ]
      },
      {
        "modified": "2021-08-27T03:22:17Z",
        "published": "2021-03-17T13:15:00Z",
        "schema_version": "1.4.0",
        "id": "PYSEC-2021-141",
        "aliases": [
          "CVE-2021-27291",
          "GHSA-pq64-v7f5-gqh8"
        ],
        "details": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "pygments",
              "purl": "pkg:pypi/pygments"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "2e7e8c4a7b318f4032493773732754e418279a14"
                  }
                ],
                "repo": "https://github.com/pygments/pygments"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "1.1"
                  },
                  {
                    "fixed": "2.7.4"
                  }
                ]
              }
            ],
            "versions": [
              "1.1",
              "1.1.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.3",
              "1.3.1",
              "1.4",
              "1.5",
              "1.6",
              "1.6rc1",
              "2.0",
              "2.0.1",
              "2.0.2",
              "2.0rc1",
              "2.1",
              "2.1.1",
              "2.1.2",
              "2.1.3",
              "2.2.0",
              "2.3.0",
              "2.3.1",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.5.1",
              "2.5.2",
              "2.6.0",
              "2.6.1",
              "2.7.0",
              "2.7.1",
              "2.7.2",
              "2.7.3"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pygments/PYSEC-2021-141.yaml"
            }
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce"
          },
          {
            "type": "FIX",
            "url": "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html"
          },
          {
            "type": "ADVISORY",
            "url": "https://www.debian.org/security/2021/dsa-4878"
          },
          {
            "type": "ADVISORY",
            "url": "https://www.debian.org/security/2021/dsa-4889"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
          },
          {
            "type": "ADVISORY",
            "url": "https://github.com/advisories/GHSA-pq64-v7f5-gqh8"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-9w8r-397f-prfh",
          "PYSEC-2021-140"
        ]
      },
      {
        "ids": [
          "GHSA-pq64-v7f5-gqh8",
          "PYSEC-2021-141"
        ]
      }
    ]
  }
]