[
  {
    "package": {
      "name": "gitpython",
      "version": "3.1.32",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "tern-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-02-16T08:14:20Z",
        "published": "2024-01-10T15:46:00Z",
        "schema_version": "1.6.0",
        "id": "GHSA-2mqj-m65w-jghx",
        "aliases": [
          "CVE-2024-22190",
          "PYSEC-2024-4"
        ],
        "summary": "Untrusted search path under some conditions on Windows allows arbitrary code execution",
        "details": "### Summary\n\nThis issue exists because of an incomplete fix for CVE-2023-40590. On Windows, GitPython uses an untrusted search path if it uses a shell to run `git`, as well as when it runs `bash.exe` to interpret hooks. If either of those features are used on Windows, a malicious `git.exe` or `bash.exe` may be run from an untrusted repository.\n\n### Details\n\nAlthough GitPython often avoids executing programs found in an untrusted search path since 3.1.33, two situations remain where this still occurs. Either can allow arbitrary code execution under some circumstances.\n\n#### When a shell is used\n\nGitPython can be told to run `git` commands through a shell rather than as direct subprocesses, by passing `shell=True` to any method that accepts it, or by both setting `Git.USE_SHELL = True` and not passing `shell=False`. Then the Windows `cmd.exe` shell process performs the path search, and GitPython does not prevent that shell from finding and running `git` in the current directory.\n\nWhen GitPython runs `git` directly rather than through a shell, the GitPython process performs the path search, and currently omits the current directory by setting `NoDefaultCurrentDirectoryInExePath` in its own environment during the `Popen` call. Although the `cmd.exe` shell will honor this environment variable when present, GitPython does not currently pass it into the shell subprocess's environment.\n\nFurthermore, because GitPython sets the subprocess CWD to the root of a repository's working tree, using a shell will run a malicious `git.exe` in an untrusted repository even if GitPython itself is run from a trusted location.\n\nThis also applies if `Git.execute` is called directly with `shell=True` (or after `Git.USE_SHELL = True`) to run any command.\n\n#### When hook scripts are run\n\nOn Windows, GitPython uses `bash.exe` to run hooks that appear to be scripts. However, unlike when running `git`, no steps are taken to avoid finding and running `bash.exe` in the current directory.\n\nThis allows the author of an untrusted fork or branch to cause a malicious `bash.exe` to be run in some otherwise safe workflows. An example of such a scenario is if the user installs a trusted hook while on a trusted branch, then switches to an untrusted feature branch (possibly from a fork) to review proposed changes. If the untrusted feature branch contains a malicious `bash.exe` and the user's current working directory is the working tree, and the user performs an action that runs the hook, then although the hook itself is uncorrupted, it runs with the malicious `bash.exe`.\n\nNote that, while `bash.exe` is a shell, this is a separate scenario from when `git` is run using the unrelated Windows `cmd.exe` shell.\n\n### PoC\n\nOn Windows, create a `git.exe` file in a repository. Then create a `Repo` object, and call any method through it (directly or indirectly) that supports the `shell` keyword argument with `shell=True`:\n\n```powershell\nmkdir testrepo\ngit init testrepo\ncp ... testrepo git.exe # Replace \"...\" with any executable of choice.\npython -c \"import git; print(git.Repo('testrepo').git.version(shell=True))\"\n```\n\nThe `git.exe` executable in the repository directory will be run.\n\nOr use no `Repo` object, but do it from the location with the `git.exe`:\n\n```powershell\ncd testrepo\npython -c \"import git; print(git.Git().version(shell=True))\"\n```\n\nThe `git.exe` executable in the current directory will be run.\n\nFor the scenario with hooks, install a hook in a repository, create a `bash.exe` file in the current directory, and perform an operation that causes GitPython to attempt to run the hook:\n\n```powershell\nmkdir testrepo\ncd testrepo\ngit init\nmv .git/hooks/pre-commit.sample .git/hooks/pre-commit\ncp ... bash.exe # Replace \"...\" with any executable of choice.\necho \"Some text\" >file.txt\ngit add file.txt\npython -c \"import git; git.Repo().index.commit('Some message')\"\n```\n\nThe `bash.exe` executable in the current directory will be run.\n\n### Impact\n\nThe greatest impact is probably in applications that set `Git.USE_SHELL = True` for historical reasons. (Undesired console windows had, in the past, been created in some kinds of applications, when it was not used.) Such an application may be vulnerable to arbitrary code execution from a malicious repository, even with no other exacerbating conditions. This is to say that, if a shell is used to run `git`, the full effect of CVE-2023-40590 is still present. Furthermore, as noted above, running the application itself from a trusted directory is not a sufficient mitigation.\n\nAn application that does not direct GitPython to use a shell to run `git` subprocesses thus avoids most of the risk. However, there is no such straightforward way to prevent GitPython from running `bash.exe` to interpret hooks. So while the conditions needed for that to be exploited are more involved, it may be harder to mitigate decisively prior to patching.\n\n### Possible solutions\n\nA straightforward approach would be to address each bug directly:\n\n- When a shell is used, pass `NoDefaultCurrentDirectoryInExePath` into the subprocess environment, because in that scenario the subprocess is the `cmd.exe` shell that itself performs the path search.\n- Set `NoDefaultCurrentDirectoryInExePath` in the GitPython process environment during the `Popen` call made to run hooks with a `bash.exe` subprocess.\n\nThese need only be done on Windows.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.41"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.33",
              "3.1.34",
              "3.1.35",
              "3.1.36",
              "3.1.37",
              "3.1.38",
              "3.1.4",
              "3.1.40",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/01/GHSA-2mqj-m65w-jghx/GHSA-2mqj-m65w-jghx.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-2mqj-m65w-jghx"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-22190"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1792"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/commit/ef3192cc414f2fd9978908454f6fd95243784c7f"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/gitpython-developers/GitPython"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2024-4.yaml"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-426"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-01-10T15:46:00Z",
          "nvd_published_at": "2024-01-11T02:15:48Z",
          "severity": "HIGH"
        }
      },
      {
        "modified": "2024-02-16T08:22:24Z",
        "published": "2023-08-30T20:09:36Z",
        "schema_version": "1.6.0",
        "id": "GHSA-cwvm-v4w8-q58c",
        "aliases": [
          "CVE-2023-41040",
          "PYSEC-2023-165"
        ],
        "summary": "Blind local file inclusion",
        "details": "### Summary\n\nIn order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system.\n\n### Details\n\nThis vulnerability is present in\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175\n\nThat code joins the base directory with a user given string without checking if the final path is located outside the base directory.\n\nI was able to exploit it from three places, but there may be more code paths that lead to it:\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/repo/base.py#L605\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/repo/base.py#L620\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/index/base.py#L1353\n\n### PoC\n\nRunning GitPython within any repo should work, here is an example with the GitPython repo.\n\n```python\nimport git\n\nr = git.Repo(\".\")\n\n# This will make GitPython read the README.md file from the root of the repo\nr.commit(\"../README.md\")\nr.tree(\"../README.md\")\nr.index.diff(\"../README.md\")\n\n# Reading /etc/random\n# WARNING: this will probably halt your system, run with caution\n# r.commit(\"../../../../../../../../../dev/random\")\n```\n\n### Impact\n\nI wasn't able to show the contents of the files (that's why \"blind\" local file inclusion), depending on how GitPython is being used, this can be used by an attacker for something _inoffensive_ as checking if a file exits, or cause a DoS by making GitPython read a big/infinite file (like `/dev/random` on Linux systems).\n\n### Possible solutions\n\nA solution would be to check that the final path isn't located outside the `repodir` path (maybe even after resolving symlinks). Maybe there could be other checks in place to make sure that the reference names are valid.\n\n---\n\n> [!NOTE]\n> This vulnerability was reported via email, and it was decided to publish it here and make it public, so the community is aware of it, and a fix can be provided.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.37"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.33",
              "3.1.34",
              "3.1.35",
              "3.1.36",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "last_known_affected_version_range": "<= 3.1.36",
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-cwvm-v4w8-q58c/GHSA-cwvm-v4w8-q58c.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-41040"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1672"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/commit/74e55ee4544867e1bd976b7df5a45869ee397b0b"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/gitpython-developers/GitPython"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-165.yaml"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-22"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-08-30T20:09:36Z",
          "nvd_published_at": "2023-08-30T22:15:09Z",
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2024-02-16T08:22:01Z",
        "published": "2023-08-29T23:33:53Z",
        "schema_version": "1.6.0",
        "id": "GHSA-wfm5-v35h-vwf4",
        "aliases": [
          "CVE-2023-40590",
          "PYSEC-2023-161"
        ],
        "summary": "GitPython untrusted search path on Windows systems leading to arbitrary code execution",
        "details": "### Summary\n\nWhen resolving a program, Python/Windows look for the current working directory, and after that the PATH environment (see big warning in https://docs.python.org/3/library/subprocess.html#popen-constructor). GitPython defaults to use the `git` command, if a user runs GitPython from a repo has a `git.exe` or `git` executable, that program will be run instead of the one in the user's `PATH`.\n\n### Details\n\nThis is more of a problem on how Python interacts with Windows systems, Linux and any other OS aren't affected by this. But probably people using GitPython usually run it from the CWD of a repo.\n\nThe execution of the `git` command happens in\n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/cmd.py#L277 \n\nhttps://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/cmd.py#L983-L996\n\nAnd there are other commands executed that should probably be aware of this problem.\n\n### PoC\n\nOn a Windows system, create a `git.exe` or `git` executable in any directory, and import or run GitPython from that directory\n\n```\npython -c \"import git\"\n```\n\nThe git executable from the current directory will be run.\n\n### Impact\n\nAn attacker can trick a user to download a repository with a malicious `git` executable, if the user runs/imports GitPython from that directory, it allows the attacker to run any arbitrary commands.\n\n### Possible solutions\n \n- Default to an absolute path for the git program on Windows, like `C:\\\\Program Files\\\\Git\\\\cmd\\\\git.EXE` (default git path installation).\n- Require users to set the `GIT_PYTHON_GIT_EXECUTABLE` environment variable on Windows systems.\n- Make this problem prominent in the documentation and advise users to never run GitPython from an untrusted repo, or set the `GIT_PYTHON_GIT_EXECUTABLE` env var to an absolute path.\n- Resolve the executable manually by only looking into the `PATH` environment variable (suggested by @Byron)\n\n---\n\n> [!NOTE]\n> This vulnerability was reported via email, and it was decided to publish it here and make it public, so the community is aware of it, and a fix can be provided.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.33"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "last_known_affected_version_range": "<= 3.1.32",
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-wfm5-v35h-vwf4/GHSA-wfm5-v35h-vwf4.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-wfm5-v35h-vwf4"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-40590"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/issues/1635"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1636"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/commit/8b75434e2c8a082cdeb4971cc6f0ee2bafec45bc"
          },
          {
            "type": "WEB",
            "url": "https://docs.python.org/3/library/subprocess.html#popen-constructor"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/gitpython-developers/GitPython"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.33"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-161.yaml"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-426"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-08-29T23:33:53Z",
          "nvd_published_at": "2023-08-28T18:15:08Z",
          "severity": "HIGH"
        }
      },
      {
        "modified": "2023-11-08T04:13:22Z",
        "published": "2023-08-28T18:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-161",
        "aliases": [
          "CVE-2023-40590",
          "GHSA-wfm5-v35h-vwf4"
        ],
        "details": " GitPython is a python library used to interact with Git repositories. When resolving a program, Python/Windows look for the current working directory, and after that the PATH environment. GitPython defaults to use the `git` command, if a user runs GitPython from a repo has a `git.exe` or `git` executable, that program will be run instead of the one in the user's `PATH`. This is more of a problem on how Python interacts with Windows systems, Linux and any other OS aren't affected by this. But probably people using GitPython usually run it from the CWD of a repo. An attacker can trick a user to download a repository with a malicious `git` executable, if the user runs/imports GitPython from that directory, it allows the attacker to run any arbitrary commands. There is no fix currently available for windows users, however there are a few mitigations. 1: Default to an absolute path for the git program on Windows, like `C:\\\\Program Files\\\\Git\\\\cmd\\\\git.EXE` (default git path installation). 2: Require users to set the `GIT_PYTHON_GIT_EXECUTABLE` environment variable on Windows systems. 3: Make this problem prominent in the documentation and advise users to never run GitPython from an untrusted repo, or set the `GIT_PYTHON_GIT_EXECUTABLE` env var to an absolute path. 4: Resolve the executable manually by only looking into the `PATH` environment variable.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.33"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/gitpython/PYSEC-2023-161.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://docs.python.org/3/library/subprocess.html#popen-constructor"
          },
          {
            "type": "ADVISORY",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-wfm5-v35h-vwf4"
          }
        ]
      },
      {
        "modified": "2023-11-08T04:13:23Z",
        "published": "2023-08-30T22:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-165",
        "aliases": [
          "CVE-2023-41040",
          "GHSA-cwvm-v4w8-q58c"
        ],
        "details": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.35"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.33",
              "3.1.34",
              "3.1.4",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/gitpython/PYSEC-2023-165.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c"
          },
          {
            "type": "WEB",
            "url": "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175"
          }
        ]
      },
      {
        "modified": "2024-01-18T16:56:49Z",
        "published": "2024-01-11T02:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2024-4",
        "aliases": [
          "CVE-2024-22190",
          "GHSA-2mqj-m65w-jghx"
        ],
        "details": "GitPython is a python library used to interact with Git repositories. There is an incomplete fix for CVE-2023-40590. On Windows, GitPython uses an untrusted search path if it uses a shell to run `git`, as well as when it runs `bash.exe` to interpret hooks. If either of those features are used on Windows, a malicious `git.exe` or `bash.exe` may be run from an untrusted repository. This issue has been patched in version 3.1.41.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "gitpython",
              "purl": "pkg:pypi/gitpython"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "ef3192cc414f2fd9978908454f6fd95243784c7f"
                  }
                ],
                "repo": "https://github.com/gitpython-developers/GitPython"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.1.41"
                  }
                ]
              }
            ],
            "versions": [
              "0.1.7",
              "0.2.0-beta1",
              "0.3.0-beta1",
              "0.3.0-beta2",
              "0.3.1-beta2",
              "0.3.2",
              "0.3.2.1",
              "0.3.2.RC1",
              "0.3.3",
              "0.3.4",
              "0.3.5",
              "0.3.6",
              "0.3.7",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.0.8",
              "2.0.9",
              "2.0.9.dev0",
              "2.0.9.dev1",
              "2.1.0",
              "2.1.1",
              "2.1.10",
              "2.1.11",
              "2.1.12",
              "2.1.13",
              "2.1.14",
              "2.1.15",
              "2.1.2",
              "2.1.3",
              "2.1.4",
              "2.1.5",
              "2.1.6",
              "2.1.7",
              "2.1.8",
              "2.1.9",
              "3.0.0",
              "3.0.1",
              "3.0.2",
              "3.0.3",
              "3.0.4",
              "3.0.5",
              "3.0.6",
              "3.0.7",
              "3.0.8",
              "3.0.9",
              "3.1.0",
              "3.1.1",
              "3.1.10",
              "3.1.11",
              "3.1.12",
              "3.1.13",
              "3.1.14",
              "3.1.15",
              "3.1.16",
              "3.1.17",
              "3.1.18",
              "3.1.19",
              "3.1.2",
              "3.1.20",
              "3.1.22",
              "3.1.23",
              "3.1.24",
              "3.1.25",
              "3.1.26",
              "3.1.27",
              "3.1.28",
              "3.1.29",
              "3.1.3",
              "3.1.30",
              "3.1.31",
              "3.1.32",
              "3.1.33",
              "3.1.34",
              "3.1.35",
              "3.1.36",
              "3.1.37",
              "3.1.38",
              "3.1.4",
              "3.1.40",
              "3.1.5",
              "3.1.6",
              "3.1.7",
              "3.1.8",
              "3.1.9"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/gitpython/PYSEC-2024-4.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-2mqj-m65w-jghx"
          },
          {
            "type": "ADVISORY",
            "url": "https://github.com/gitpython-developers/GitPython/pull/1792"
          },
          {
            "type": "FIX",
            "url": "https://github.com/gitpython-developers/GitPython/commit/ef3192cc414f2fd9978908454f6fd95243784c7f"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-2mqj-m65w-jghx",
          "PYSEC-2024-4"
        ],
        "aliases": [
          "CVE-2024-22190",
          "GHSA-2mqj-m65w-jghx",
          "PYSEC-2024-4"
        ],
        "max_severity": "7.8"
      },
      {
        "ids": [
          "GHSA-cwvm-v4w8-q58c",
          "PYSEC-2023-165"
        ],
        "aliases": [
          "CVE-2023-41040",
          "GHSA-cwvm-v4w8-q58c",
          "PYSEC-2023-165"
        ],
        "max_severity": "6.5"
      },
      {
        "ids": [
          "GHSA-wfm5-v35h-vwf4",
          "PYSEC-2023-161"
        ],
        "aliases": [
          "CVE-2023-40590",
          "GHSA-wfm5-v35h-vwf4",
          "PYSEC-2023-161"
        ],
        "max_severity": "7.8"
      }
    ]
  },
  {
    "package": {
      "name": "idna",
      "version": "3.4",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "tern-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-07-11T18:46:06Z",
        "published": "2024-04-11T21:32:40Z",
        "schema_version": "1.6.0",
        "id": "GHSA-jjg7-2v4v-x38h",
        "aliases": [
          "CVE-2024-3651",
          "PYSEC-2024-60"
        ],
        "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
        "details": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "idna",
              "purl": "pkg:pypi/idna"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "3.7"
                  }
                ]
              }
            ],
            "versions": [
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "0.7",
              "0.8",
              "0.9",
              "1.0",
              "1.1",
              "2.0",
              "2.1",
              "2.10",
              "2.2",
              "2.3",
              "2.4",
              "2.5",
              "2.6",
              "2.7",
              "2.8",
              "2.9",
              "3.0",
              "3.1",
              "3.2",
              "3.3",
              "3.4",
              "3.5",
              "3.6"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/04/GHSA-jjg7-2v4v-x38h/GHSA-jjg7-2v4v-x38h.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          },
          {
            "type": "CVSS_V4",
            "score": "CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3651"
          },
          {
            "type": "WEB",
            "url": "https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/kjd/idna"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/idna/PYSEC-2024-60.yaml"
          },
          {
            "type": "WEB",
            "url": "https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-400"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-04-11T21:32:40Z",
          "nvd_published_at": "2024-07-07T18:15:09Z",
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2024-07-11T17:42:33Z",
        "published": "2024-07-07T18:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2024-60",
        "aliases": [
          "CVE-2024-3651",
          "GHSA-jjg7-2v4v-x38h"
        ],
        "details": "A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "idna",
              "purl": "pkg:pypi/idna"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"
                  }
                ],
                "repo": "https://github.com/kjd/idna"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0.1"
                  }
                ]
              }
            ],
            "versions": [
              "0.1",
              "0.2",
              "0.3",
              "0.4",
              "0.5",
              "0.6",
              "0.7",
              "0.8",
              "0.9",
              "1.0",
              "1.1",
              "2.0",
              "2.1",
              "2.10",
              "2.2",
              "2.3",
              "2.4",
              "2.5",
              "2.6",
              "2.7",
              "2.8",
              "2.9",
              "3.0",
              "3.1",
              "3.2",
              "3.3",
              "3.4",
              "3.5",
              "3.6"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/idna/PYSEC-2024-60.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
          }
        ],
        "references": [
          {
            "type": "FIX",
            "url": "https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"
          },
          {
            "type": "FIX",
            "url": "https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-jjg7-2v4v-x38h",
          "PYSEC-2024-60"
        ],
        "aliases": [
          "CVE-2024-3651",
          "GHSA-jjg7-2v4v-x38h",
          "PYSEC-2024-60"
        ],
        "max_severity": "7.5"
      }
    ]
  },
  {
    "package": {
      "name": "requests",
      "version": "2.31.0",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "tern-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-06-21T16:29:28Z",
        "published": "2024-05-20T20:15:00Z",
        "schema_version": "1.6.0",
        "id": "GHSA-9wx4-h78v-vm56",
        "aliases": [
          "CGA-77h5-pgh2-r2fg",
          "CGA-p79x-5pxg-f77m",
          "CGA-v542-whj6-7mj4",
          "CVE-2024-35195"
        ],
        "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
        "details": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "requests",
              "purl": "pkg:pypi/requests"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "2.32.0"
                  }
                ]
              }
            ],
            "versions": [
              "0.0.1",
              "0.10.0",
              "0.10.1",
              "0.10.2",
              "0.10.3",
              "0.10.4",
              "0.10.6",
              "0.10.7",
              "0.10.8",
              "0.11.1",
              "0.11.2",
              "0.12.0",
              "0.12.01",
              "0.12.1",
              "0.13.0",
              "0.13.1",
              "0.13.2",
              "0.13.3",
              "0.13.4",
              "0.13.5",
              "0.13.6",
              "0.13.7",
              "0.13.8",
              "0.13.9",
              "0.14.0",
              "0.14.1",
              "0.14.2",
              "0.2.0",
              "0.2.1",
              "0.2.2",
              "0.2.3",
              "0.2.4",
              "0.3.0",
              "0.3.1",
              "0.3.2",
              "0.3.3",
              "0.3.4",
              "0.4.0",
              "0.4.1",
              "0.5.0",
              "0.5.1",
              "0.6.0",
              "0.6.1",
              "0.6.2",
              "0.6.3",
              "0.6.4",
              "0.6.5",
              "0.6.6",
              "0.7.0",
              "0.7.1",
              "0.7.2",
              "0.7.3",
              "0.7.4",
              "0.7.5",
              "0.7.6",
              "0.8.0",
              "0.8.1",
              "0.8.2",
              "0.8.3",
              "0.8.4",
              "0.8.5",
              "0.8.6",
              "0.8.7",
              "0.8.8",
              "0.8.9",
              "0.9.0",
              "0.9.1",
              "0.9.2",
              "0.9.3",
              "1.0.0",
              "1.0.1",
              "1.0.2",
              "1.0.3",
              "1.0.4",
              "1.1.0",
              "1.2.0",
              "1.2.1",
              "1.2.2",
              "1.2.3",
              "2.0.0",
              "2.0.1",
              "2.1.0",
              "2.10.0",
              "2.11.0",
              "2.11.1",
              "2.12.0",
              "2.12.1",
              "2.12.2",
              "2.12.3",
              "2.12.4",
              "2.12.5",
              "2.13.0",
              "2.14.0",
              "2.14.1",
              "2.14.2",
              "2.15.0",
              "2.15.1",
              "2.16.0",
              "2.16.1",
              "2.16.2",
              "2.16.3",
              "2.16.4",
              "2.16.5",
              "2.17.0",
              "2.17.1",
              "2.17.2",
              "2.17.3",
              "2.18.0",
              "2.18.1",
              "2.18.2",
              "2.18.3",
              "2.18.4",
              "2.19.0",
              "2.19.1",
              "2.2.0",
              "2.2.1",
              "2.20.0",
              "2.20.1",
              "2.21.0",
              "2.22.0",
              "2.23.0",
              "2.24.0",
              "2.25.0",
              "2.25.1",
              "2.26.0",
              "2.27.0",
              "2.27.1",
              "2.28.0",
              "2.28.1",
              "2.28.2",
              "2.29.0",
              "2.3.0",
              "2.30.0",
              "2.31.0",
              "2.4.0",
              "2.4.1",
              "2.4.2",
              "2.4.3",
              "2.5.0",
              "2.5.1",
              "2.5.2",
              "2.5.3",
              "2.6.0",
              "2.6.1",
              "2.6.2",
              "2.7.0",
              "2.8.0",
              "2.8.1",
              "2.9.0",
              "2.9.1",
              "2.9.2"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/05/GHSA-9wx4-h78v-vm56/GHSA-9wx4-h78v-vm56.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
          },
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/pull/6655"
          },
          {
            "type": "WEB",
            "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/psf/requests"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-670"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-05-20T20:15:00Z",
          "nvd_published_at": "2024-05-20T21:15:09Z",
          "severity": "MODERATE"
        }
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-9wx4-h78v-vm56"
        ],
        "aliases": [
          "CGA-77h5-pgh2-r2fg",
          "CGA-p79x-5pxg-f77m",
          "CGA-v542-whj6-7mj4",
          "CVE-2024-35195",
          "GHSA-9wx4-h78v-vm56"
        ],
        "max_severity": "5.6"
      }
    ]
  },
  {
    "package": {
      "name": "urllib3",
      "version": "2.0.3",
      "ecosystem": "PyPI"
    },
    "dependency_groups": [
      "tern-requirements"
    ],
    "vulnerabilities": [
      {
        "modified": "2024-06-25T02:48:33Z",
        "published": "2024-06-17T21:37:20Z",
        "schema_version": "1.6.0",
        "id": "GHSA-34jh-p97f-mpxf",
        "aliases": [
          "CGA-2vvm-h2g8-jrwc",
          "CGA-32mf-hm7c-cqmg",
          "CGA-3ggr-w55x-hf5j",
          "CGA-5v3j-934q-gj4m",
          "CGA-69g4-mv22-46cq",
          "CGA-8f64-fgpv-jxj2",
          "CGA-grjq-jh3q-2p7g",
          "CGA-gwpm-7fhq-3wh2",
          "CGA-h28r-8q2c-xq96",
          "CGA-j235-35vq-wrm8",
          "CGA-mrr8-97mj-749q",
          "CGA-rqhm-766h-p289",
          "CGA-w3h9-h7jv-6q22",
          "CVE-2024-37891"
        ],
        "summary": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects ",
        "details": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected.\n\nHowever, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.\n\nBecause this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident.\n\nUsers should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support.\n* Not disabling HTTP redirects.\n* Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin.\n\n## Remediation\n\n* Using the `Proxy-Authorization` header with urllib3's `ProxyManager`.\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Proxy-Authorization` header.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.19"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.17",
              "1.26.18",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/06/GHSA-34jh-p97f-mpxf/GHSA-34jh-p97f-mpxf.json"
            }
          },
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.2.2"
                  }
                ]
              }
            ],
            "versions": [
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6",
              "2.0.7",
              "2.1.0",
              "2.2.0",
              "2.2.1"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2024/06/GHSA-34jh-p97f-mpxf/GHSA-34jh-p97f-mpxf.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/urllib3/urllib3"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-669"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2024-06-17T21:37:20Z",
          "nvd_published_at": "2024-06-17T20:15:13Z",
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2024-02-21T05:25:29Z",
        "published": "2023-10-17T20:15:25Z",
        "schema_version": "1.6.0",
        "id": "GHSA-g4mx-q9vg-27p4",
        "aliases": [
          "CVE-2023-45803",
          "PYSEC-2023-212"
        ],
        "summary": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
        "details": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.\n",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.7"
                  }
                ]
              }
            ],
            "versions": [
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-g4mx-q9vg-27p4/GHSA-g4mx-q9vg-27p4.json"
            }
          },
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.18"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.17",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-g4mx-q9vg-27p4/GHSA-g4mx-q9vg-27p4.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/urllib3/urllib3"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/releases/tag/1.26.18"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/releases/tag/2.0.7"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX"
          },
          {
            "type": "WEB",
            "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-200"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-10-17T20:15:25Z",
          "nvd_published_at": "2023-10-17T20:15:10Z",
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2024-02-18T05:30:37Z",
        "published": "2023-10-02T23:27:05Z",
        "schema_version": "1.6.0",
        "id": "GHSA-v845-jxx5-vc9f",
        "aliases": [
          "CVE-2023-43804",
          "PYSEC-2023-192"
        ],
        "summary": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
        "details": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.6"
                  }
                ]
              }
            ],
            "versions": [
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-v845-jxx5-vc9f/GHSA-v845-jxx5-vc9f.json"
            }
          },
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.17"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1"
            ],
            "database_specific": {
              "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/10/GHSA-v845-jxx5-vc9f/GHSA-v845-jxx5-vc9f.json"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N"
          }
        ],
        "references": [
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
          },
          {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
          },
          {
            "type": "WEB",
            "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
          },
          {
            "type": "WEB",
            "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"
          },
          {
            "type": "PACKAGE",
            "url": "https://github.com/urllib3/urllib3"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY"
          },
          {
            "type": "WEB",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ"
          }
        ],
        "database_specific": {
          "cwe_ids": [
            "CWE-200"
          ],
          "github_reviewed": true,
          "github_reviewed_at": "2023-10-02T23:27:05Z",
          "nvd_published_at": "2023-10-04T17:15:10Z",
          "severity": "MODERATE"
        }
      },
      {
        "modified": "2023-11-08T04:13:33Z",
        "published": "2023-10-04T17:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-192",
        "aliases": [
          "CVE-2023-43804",
          "GHSA-v845-jxx5-vc9f"
        ],
        "details": "urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "644124ecd0b6e417c527191f866daa05a5a2056d"
                  },
                  {
                    "fixed": "01220354d389cd05474713f8c982d05c9b17aafb"
                  }
                ],
                "repo": "https://github.com/urllib3/urllib3"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.6"
                  },
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.17"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/urllib3/PYSEC-2023-192.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N"
          }
        ],
        "references": [
          {
            "type": "FIX",
            "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
          },
          {
            "type": "ADVISORY",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
          },
          {
            "type": "FIX",
            "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
          },
          {
            "type": "WEB",
            "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
          }
        ]
      },
      {
        "modified": "2023-11-08T04:13:39Z",
        "published": "2023-10-17T20:15:00Z",
        "schema_version": "1.6.0",
        "id": "PYSEC-2023-212",
        "aliases": [
          "CVE-2023-45803",
          "GHSA-g4mx-q9vg-27p4"
        ],
        "details": "urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.\n",
        "affected": [
          {
            "package": {
              "ecosystem": "PyPI",
              "name": "urllib3",
              "purl": "pkg:pypi/urllib3"
            },
            "ranges": [
              {
                "type": "GIT",
                "events": [
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "4e98d57809dacab1cbe625fddeec1a290c478ea9"
                  }
                ],
                "repo": "https://github.com/urllib3/urllib3"
              },
              {
                "type": "ECOSYSTEM",
                "events": [
                  {
                    "introduced": "2.0.0"
                  },
                  {
                    "fixed": "2.0.7"
                  },
                  {
                    "introduced": "0"
                  },
                  {
                    "fixed": "1.26.18"
                  }
                ]
              }
            ],
            "versions": [
              "0.2",
              "0.3",
              "0.3.1",
              "0.4.0",
              "0.4.1",
              "1.0",
              "1.0.1",
              "1.0.2",
              "1.1",
              "1.10",
              "1.10.1",
              "1.10.2",
              "1.10.3",
              "1.10.4",
              "1.11",
              "1.12",
              "1.13",
              "1.13.1",
              "1.14",
              "1.15",
              "1.15.1",
              "1.16",
              "1.17",
              "1.18",
              "1.18.1",
              "1.19",
              "1.19.1",
              "1.2",
              "1.2.1",
              "1.2.2",
              "1.20",
              "1.21",
              "1.21.1",
              "1.22",
              "1.23",
              "1.24",
              "1.24.1",
              "1.24.2",
              "1.24.3",
              "1.25",
              "1.25.1",
              "1.25.10",
              "1.25.11",
              "1.25.2",
              "1.25.3",
              "1.25.4",
              "1.25.5",
              "1.25.6",
              "1.25.7",
              "1.25.8",
              "1.25.9",
              "1.26.0",
              "1.26.1",
              "1.26.10",
              "1.26.11",
              "1.26.12",
              "1.26.13",
              "1.26.14",
              "1.26.15",
              "1.26.16",
              "1.26.17",
              "1.26.2",
              "1.26.3",
              "1.26.4",
              "1.26.5",
              "1.26.6",
              "1.26.7",
              "1.26.8",
              "1.26.9",
              "1.3",
              "1.4",
              "1.5",
              "1.6",
              "1.7",
              "1.7.1",
              "1.8",
              "1.8.2",
              "1.8.3",
              "1.9",
              "1.9.1",
              "2.0.0",
              "2.0.1",
              "2.0.2",
              "2.0.3",
              "2.0.4",
              "2.0.5",
              "2.0.6"
            ],
            "database_specific": {
              "source": "https://github.com/pypa/advisory-database/blob/main/vulns/urllib3/PYSEC-2023-212.yaml"
            }
          }
        ],
        "severity": [
          {
            "type": "CVSS_V3",
            "score": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N"
          }
        ],
        "references": [
          {
            "type": "ADVISORY",
            "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
          },
          {
            "type": "WEB",
            "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
          },
          {
            "type": "FIX",
            "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
          },
          {
            "type": "ARTICLE",
            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/"
          }
        ]
      }
    ],
    "groups": [
      {
        "ids": [
          "GHSA-34jh-p97f-mpxf"
        ],
        "aliases": [
          "CGA-2vvm-h2g8-jrwc",
          "CGA-32mf-hm7c-cqmg",
          "CGA-3ggr-w55x-hf5j",
          "CGA-5v3j-934q-gj4m",
          "CGA-69g4-mv22-46cq",
          "CGA-8f64-fgpv-jxj2",
          "CGA-grjq-jh3q-2p7g",
          "CGA-gwpm-7fhq-3wh2",
          "CGA-h28r-8q2c-xq96",
          "CGA-j235-35vq-wrm8",
          "CGA-mrr8-97mj-749q",
          "CGA-rqhm-766h-p289",
          "CGA-w3h9-h7jv-6q22",
          "CVE-2024-37891",
          "GHSA-34jh-p97f-mpxf"
        ],
        "max_severity": "4.4"
      },
      {
        "ids": [
          "GHSA-g4mx-q9vg-27p4",
          "PYSEC-2023-212"
        ],
        "aliases": [
          "CVE-2023-45803",
          "GHSA-g4mx-q9vg-27p4",
          "PYSEC-2023-212"
        ],
        "max_severity": "4.2"
      },
      {
        "ids": [
          "GHSA-v845-jxx5-vc9f",
          "PYSEC-2023-192"
        ],
        "aliases": [
          "CVE-2023-43804",
          "GHSA-v845-jxx5-vc9f",
          "PYSEC-2023-192"
        ],
        "max_severity": "8.1"
      }
    ]
  }
]